version: "3.8"
services:
  mongodb:
    image: "mongo"
    volumes:
      - data:/data/db
  app:
    build: "."
    ports:
      - "3000:3000"
    volumes:
      - "/app/node_modules"
      - ".:/app"
    depends_on: 
      - mongodb
volumes:
  data: